import Handlebars from 'handlebars';
import { IRProject } from '../../ir/src';

export class GoGenerator {
    private template: Handlebars.TemplateDelegate;

    constructor() {
        this.template = Handlebars.compile(this.getTemplate(), { noEscape: true });
        this.registerHelpers();
    }

    generate(project: IRProject): Map<string, string> {
        const files = new Map<string, string>();
        
        // 1. Models/DTOs
        if (project.dtos.length > 0) {
            files.set('internal/models/models.go', this.generateModels(project));
        }

        // 2. Controllers
        if (project.controllers.length > 0) {
            files.set('internal/controllers/controllers.go', this.generateControllers(project));
        }

        // 3. Main (cmd)
        files.set('cmd/main.go', this.generateMain(project));

        return files;
    }

    private generateModels(project: IRProject): string {
        const template = Handlebars.compile(`package models

{{#each dtos}}
type {{name}} struct {
    {{#each fields}}
    {{capitalize name}} {{mapType type}} \`json:"{{name}}"\`
    {{/each}}
}
{{/each}}
`);
        return template(project);
    }

    private generateControllers(project: IRProject): string {
        const template = Handlebars.compile(`package controllers

import (
    "github.com/gofiber/fiber/v2"
    {{#if (hasHttpCalls controllers)}}
    "net/http"
    "net/url"
    {{/if}}
    {{#if (hasEnvVars controllers)}}
    "os"
    {{/if}}
)

{{#each controllers}}
type {{name}} struct {}

func Register{{name}}(app *fiber.App) {
    controller := &{{name}}{}
    {{#each routes}}
    app.{{capitalize (lowercased method)}}("{{../basePath}}{{path}}", controller.{{capitalize handlerName}})
    {{/each}}
}

{{#each routes}}
func (c *{{../name}}) {{capitalize handlerName}}(ctx *fiber.Ctx) error {
    {{#each parameters}}
    {{#if (eq in "body")}}
    var {{name}} interface{} // TODO: Map to actual model
    if err := ctx.BodyParser(&{{name}}); err != nil {
        return ctx.Status(400).JSON(fiber.Map{"error": err.Error()})
    }
    {{/if}}
    {{/each}}
    
    {{#each body}}
    {{#if (eq kind "HttpCall")}}
    // Axios.{{method}}("{{url}}") -> Go net/http
    {{#if resultVar}}{{resultVar}}, {{/if}}err := http.DefaultClient.Do(&http.Request{Method: "{{method}}", URL: parseURL("{{url}}")})
    if err != nil {
        return ctx.Status(500).SendString(err.Error())
    }
    {{#if resultVar}}
    // TODO: Parse response body into {{resultVar}}
    {{else}}
    defer resp.Body.Close()
    {{/if}}
    {{/if}}

    {{#if (eq kind "EnvVar")}}
    // process.env.{{name}} -> os.Getenv("{{name}}")
    _ = os.Getenv("{{name}}")
    {{/if}}
    {{/each}}

    // Generated by ts4go
    return ctx.JSON(fiber.Map{"status": "ok", "controller": "{{../name}}", "method": "{{handlerName}}"})
}
{{/each}}

{{/each}}

{{#if (hasHttpCalls controllers)}}
func parseURL(u string) *url.URL {
    p, _ := url.Parse(u)
    return p
}
{{/if}}
`, { noEscape: true });
        return template(project);
    }

    private generateMain(project: IRProject): string {
        const template = Handlebars.compile(`package main

import (
    "github.com/gofiber/fiber/v2"
    "ts4go-api/internal/controllers"
)

func main() {
    app := fiber.New()

    // Register controllers
    {{#each controllers}}
    controllers.Register{{name}}(app)
    {{/each}}

    app.Listen(":3000")
}
`, { noEscape: true });
        return template(project);
    }

    private registerHelpers() {
        Handlebars.registerHelper('capitalize', (str: string) => {
            if (!str) return '';
            return str.charAt(0).toUpperCase() + str.slice(1);
        });
        Handlebars.registerHelper('lowercased', (str: string) => {
            if (!str) return '';
            return str.toLowerCase();
        });
        Handlebars.registerHelper('eq', (a: any, b: any) => a === b);
        Handlebars.registerHelper('mapType', (type: any) => {
            const name = type.name;
            switch (name) {
                case 'string': return 'string';
                case 'number': return 'float64';
                case 'boolean': return 'bool';
                default: return name;
            }
        });
        Handlebars.registerHelper('hasHttpCalls', (controllers: any[]) => {
            return controllers.some(c => c.routes.some((r: any) => r.body.some((s: any) => s.kind === 'HttpCall')));
        });
        Handlebars.registerHelper('hasEnvVars', (controllers: any[]) => {
            return controllers.some(c => c.routes.some((r: any) => r.body.some((s: any) => s.kind === 'EnvVar')));
        });
    }

    private getTemplate(): string {
        return `package main

import (
    "github.com/gofiber/fiber/v2"
    {{#if (hasHttpCalls controllers)}}
    "net/http"
    "net/url"
    {{/if}}
    {{#if (hasEnvVars controllers)}}
    "os"
    {{/if}}
)

{{#each dtos}}
type {{name}} struct {
    {{#each fields}}
    {{capitalize name}} {{mapType type}} \`json:"{{name}}"\`
    {{/each}}
}
{{/each}}

{{#each controllers}}
type {{name}} struct {}

func Register{{name}}(app *fiber.App) {
    controller := &{{name}}{}
    {{#each routes}}
    app.{{capitalize (lowercased method)}}("{{../basePath}}{{path}}", controller.{{capitalize handlerName}})
    {{/each}}
}

{{#each routes}}
func (c *{{../name}}) {{capitalize handlerName}}(ctx *fiber.Ctx) error {
    {{#each parameters}}
    {{#if (eq in "body")}}
    var {{name}} {{mapType type}}
    if err := ctx.BodyParser(&{{name}}); err != nil {
        return ctx.Status(400).JSON(fiber.Map{"error": err.Error()})
    }
    {{/if}}
    {{/each}}
    
    {{#each body}}
    {{#if (eq kind "HttpCall")}}
    // Axios.{{method}}("{{url}}") -> Go net/http
    {{#if resultVar}}{{resultVar}}, {{/if}}err := http.DefaultClient.Do(&http.Request{Method: "{{method}}", URL: parseURL("{{url}}")})
    if err != nil {
        return ctx.Status(500).SendString(err.Error())
    }
    {{#if resultVar}}
    // TODO: Parse response body into {{resultVar}}
    {{else}}
    defer resp.Body.Close()
    {{/if}}
    {{/if}}

    {{#if (eq kind "EnvVar")}}
    // process.env.{{name}} -> os.Getenv("{{name}}")
    _ = os.Getenv("{{name}}")
    {{/if}}
    {{/each}}

    // Generated by ts2go
    return ctx.JSON(fiber.Map{"status": "ok", "controller": "{{../name}}", "method": "{{handlerName}}"})
}
{{/each}}

{{/each}}

func parseURL(u string) *url.URL {
    p, _ := url.Parse(u)
    return p
}

func main() {
    app := fiber.New()

    {{#each controllers}}
    Register{{name}}(app)
    {{/each}}

    app.Listen(":3000")
}
`;
    }
}
