import Handlebars from 'handlebars';
import { IRProject } from '../../ir/src';

export class GoGenerator {
    private template: Handlebars.TemplateDelegate;

    constructor() {
        this.template = Handlebars.compile(this.getTemplate(), { noEscape: true });
        this.registerHelpers();
    }

    generate(project: IRProject): Map<string, string> {
        const files = new Map<string, string>();
        
        // 1. Models/DTOs
        if (project.dtos.length > 0) {
            files.set('internal/models/models.go', this.generateModels(project));
        }

        // 2. Controllers
        if (project.controllers.length > 0) {
            files.set('internal/controllers/controllers.go', this.generateControllers(project));
        }

        // 3. Logic/Classes
        if (project.classes.length > 0) {
            files.set('internal/controllers/logic.go', this.generateClasses(project));
        }

        // 4. Main (cmd)
        files.set('cmd/main.go', this.generateMain(project));

        return files;
    }

    private generateModels(project: IRProject): string {
        const template = Handlebars.compile(`package models

{{#each dtos}}
type {{name}} struct {
    {{#each fields}}
    {{capitalize name}} {{mapType type}} \`json:"{{name}}"\`
    {{/each}}
}
{{/each}}
`);
        return template(project);
    }

    private generateControllers(project: IRProject): string {
        const template = Handlebars.compile(`package controllers

import (
    "github.com/gofiber/fiber/v2"
    {{#if (hasHttpCalls controllers)}}
    "net/http"
    "net/url"
    {{/if}}
    {{#if (hasEnvVars controllers)}}
    "os"
    {{/if}}
)

{{#each controllers}}
type {{name}} struct {}

func Register{{name}}(app *fiber.App) {
    controller := &{{name}}{}
    {{#each routes}}
    app.{{capitalize (lowercased method)}}("{{../basePath}}{{path}}", controller.{{capitalize handlerName}})
    {{/each}}
}

{{#each routes}}
func (c *{{../name}}) {{capitalize handlerName}}(ctx *fiber.Ctx) error {
    {{#each parameters}}
    {{#if (eq in "body")}}
    var {{name}} interface{} // TODO: Map to actual model
    if err := ctx.BodyParser(&{{name}}); err != nil {
        return ctx.Status(400).JSON(fiber.Map{"error": err.Error()})
    }
    {{/if}}
    {{/each}}
    
    {{#each body}}
    {{#if (eq kind "HttpCall")}}
    // Axios.{{method}}("{{url}}") -> Go net/http
    {{#if resultVar}}{{resultVar}}, {{/if}}err := http.DefaultClient.Do(&http.Request{Method: "{{method}}", URL: parseURL("{{url}}")})
    if err != nil {
        return ctx.Status(500).SendString(err.Error())
    }
    {{#if resultVar}}
    // TODO: Parse response body into {{resultVar}}
    {{else}}
    defer resp.Body.Close()
    {{/if}}
    {{/if}}

    {{#if (eq kind "EnvVar")}}
    // process.env.{{name}} -> os.Getenv("{{name}}")
    _ = os.Getenv("{{name}}")
    {{/if}}

    {{#if (eq kind "Assignment")}}
    {{variableName}} := {{{mapExpression expression}}}
    {{/if}}

    {{#if (eq kind "Return")}}
    return ctx.JSON({{{mapReturnValue value}}})
    {{/if}}
    {{/each}}

    {{#unless (hasReturn body)}}
    // Generated by ts4go
    return ctx.JSON(fiber.Map{"status": "ok", "controller": "{{../name}}", "method": "{{handlerName}}"})
    {{/unless}}
}
{{/each}}

{{/each}}

{{#if (hasHttpCalls controllers)}}
func parseURL(u string) *url.URL {
    p, _ := url.Parse(u)
    return p
}
{{/if}}
`, { noEscape: true });
        return template(project);
    }

    private generateClasses(project: IRProject): string {
        const template = Handlebars.compile(`package controllers

import (
    "github.com/gofiber/fiber/v2"
)

{{#each classes}}
type {{name}} struct {}

{{#each methods}}
func (c *{{../name}}) {{capitalize name}}({{#each parameters}}{{name}} {{mapType type}}{{#unless @last}}, {{/unless}}{{/each}}) interface{} {
    {{#each body}}
    {{#if (eq kind "Assignment")}}
    {{variableName}} := {{{mapExpression expression}}}
    {{/if}}

    {{#if (eq kind "Return")}}
    return {{{mapReturnValue value}}}
    {{/if}}
    {{/each}}
    {{#unless (hasReturn body)}}
    return nil
    {{/unless}}
}
{{/each}}
{{/each}}
`, { noEscape: true });
        return template(project);
    }

    private generateMain(project: IRProject): string {
        const template = Handlebars.compile(`package main

import (
    "github.com/gofiber/fiber/v2"
    "ts4go-api/internal/controllers"
)

func main() {
    app := fiber.New()

    // Register controllers
    {{#each controllers}}
    controllers.Register{{name}}(app)
    {{/each}}

    app.Listen(":3000")
}
`, { noEscape: true });
        return template(project);
    }

    private registerHelpers() {
        Handlebars.registerHelper('capitalize', (str: string) => {
            if (!str) return '';
            return str.charAt(0).toUpperCase() + str.slice(1);
        });
        Handlebars.registerHelper('lowercased', (str: string) => {
            if (!str) return '';
            return str.toLowerCase();
        });
        Handlebars.registerHelper('eq', (a: any, b: any) => a === b);
        Handlebars.registerHelper('mapType', (type: any) => {
            const name = type.name;
            switch (name) {
                case 'string': return 'string';
                case 'number': return 'float64';
                case 'boolean': return 'bool';
                default: return name;
            }
        });
        Handlebars.registerHelper('hasHttpCalls', (controllers: any[]) => {
            return controllers.some(c => c.routes.some((r: any) => r.body.some((s: any) => s.kind === 'HttpCall')));
        });
        Handlebars.registerHelper('hasEnvVars', (controllers: any[]) => {
            return controllers.some(c => c.routes.some((r: any) => r.body.some((s: any) => s.kind === 'EnvVar')));
        });
        Handlebars.registerHelper('hasReturn', (body: any[]) => {
            return body.some((s: any) => s.kind === 'Return');
        });
        Handlebars.registerHelper('mapReturnValue', (value: string) => {
            if (!value) return 'nil';
            // Remove ALL comments from the string first (multiline)
            let noComments = value.replace(/\/\/.*$/gm, '').trim();
            
            // Capitalize method calls: useCase.execute() -> useCase.Execute()
            noComments = noComments.replace(/\.([a-z])([a-zA-Z0-9]*)\(/g, (match: string, p1: string, p2: string) => `.${p1.toUpperCase()}${p2}(`);

            if (noComments.startsWith('{') && noComments.endsWith('}')) {
                const inner = noComments.slice(1, -1).trim();
                const pairs = inner.split(',').map(p => {
                    const parts = p.split(':');
                    if (parts.length < 2) return '';
                    const k = parts[0].trim().replace(/['"]/g, '');
                    let v = parts.slice(1).join(':').trim();
                    // Basic JS to Go literal conversion
                    if (v.startsWith("'") && v.endsWith("'")) v = `"${v.slice(1, -1)}"`;
                    return `"${k}": ${v}`;
                }).filter(p => p !== '');
                return `fiber.Map{${pairs.join(', ')}}`;
            }
            // Generic single quote to double quote conversion for strings
            if (noComments.startsWith("'") && noComments.endsWith("'")) {
                return `"${noComments.slice(1, -1)}"`;
            }
            return noComments;
        });
        Handlebars.registerHelper('mapExpression', (expr: any) => {
            if (!expr) return '';
            if (expr.kind === 'Raw') {
                let val = expr.value.trim();
                // Capitalize method calls: useCase.execute() -> useCase.Execute()
                val = val.replace(/\.([a-z])([a-zA-Z0-9]*)\(/g, (match: string, p1: string, p2: string) => `.${p1.toUpperCase()}${p2}(`);

                // new UseCase() -> &UseCase{}
                if (val.startsWith('new ')) {
                    const className = val.replace('new ', '').replace('()', '').trim();
                    return `&${className}{}`;
                }
                return val;
            }
            return '';
        });
    }

    private getTemplate(): string {
        return `package main

import (
    "github.com/gofiber/fiber/v2"
    {{#if (hasHttpCalls controllers)}}
    "net/http"
    "net/url"
    {{/if}}
    {{#if (hasEnvVars controllers)}}
    "os"
    {{/if}}
)

{{#each dtos}}
type {{name}} struct {
    {{#each fields}}
    {{capitalize name}} {{mapType type}} \`json:"{{name}}"\`
    {{/each}}
}
{{/each}}

{{#each controllers}}
type {{name}} struct {}

func Register{{name}}(app *fiber.App) {
    controller := &{{name}}{}
    {{#each routes}}
    app.{{capitalize (lowercased method)}}("{{../basePath}}{{path}}", controller.{{capitalize handlerName}})
    {{/each}}
}

{{#each routes}}
func (c *{{../name}}) {{capitalize handlerName}}(ctx *fiber.Ctx) error {
    {{#each parameters}}
    {{#if (eq in "body")}}
    var {{name}} {{mapType type}}
    if err := ctx.BodyParser(&{{name}}); err != nil {
        return ctx.Status(400).JSON(fiber.Map{"error": err.Error()})
    }
    {{/if}}
    {{/each}}
    
    {{#each body}}
    {{#if (eq kind "HttpCall")}}
    // Axios.{{method}}("{{url}}") -> Go net/http
    {{#if resultVar}}{{resultVar}}, {{/if}}err := http.DefaultClient.Do(&http.Request{Method: "{{method}}", URL: parseURL("{{url}}")})
    if err != nil {
        return ctx.Status(500).SendString(err.Error())
    }
    {{#if resultVar}}
    // TODO: Parse response body into {{resultVar}}
    {{else}}
    defer resp.Body.Close()
    {{/if}}
    {{/if}}

    {{#if (eq kind "EnvVar")}}
    // process.env.{{name}} -> os.Getenv("{{name}}")
    _ = os.Getenv("{{name}}")
    {{/if}}

    {{#if (eq kind "Return")}}
    return ctx.JSON({{{mapReturnValue value}}})
    {{/if}}
    {{/each}}

    {{#unless (hasReturn body)}}
    // Generated by ts2go
    return ctx.JSON(fiber.Map{"status": "ok", "controller": "{{../name}}", "method": "{{handlerName}}"})
    {{/unless}}
}
{{/each}}

{{/each}}

func parseURL(u string) *url.URL {
    p, _ := url.Parse(u)
    return p
}

func main() {
    app := fiber.New()

    {{#each controllers}}
    Register{{name}}(app)
    {{/each}}

    app.Listen(":3000")
}
`;
    }
}
